export const lostPetsDatabase = [
    {
        id: 1,
        name: 'Μπάμπης',
        type: 'dog',
        breed: 'Golden Retriever',
        area: 'Κέντρο Αθήνας, Πλατεία Συντάγματος',
        dateLost: '05/11/2025',
        color: 'Χρυσαφί',
        microchip: 'GR123456789012345',
        description: 'Φιλικός, φοράει πράσινο περιλαίμιο.',
        traits: ['Ήρεμος', 'Αγαπά παιδιά', 'Σπιτικός'],
        age: '2',
        gender: 'male',
    },
    {
        id: 2,
        name: 'Φιφή',
        type: 'cat',
        breed: 'Περσική',
        area: 'Θεσσαλονίκη, Καλαμαριά',
        dateLost: '10/11/2025',
        color: 'Λευκό',
        microchip: 'GR987654321000111',
        description: 'Τρομάζει εύκολα, προτιμά ήρεμα περιβάλλοντα.',
        traits: ['Πολύ ήρεμη', 'Αγαπά λιχουδιές'],
        age: '3',
        gender: 'female',
    },
    {
        id: 3,
        name: 'Ρεξ',
        type: 'dog',
        breed: 'Λαμπραντόρ',
        area: 'Πάτρα, Κέντρο',
        dateLost: '08/11/2025',
        color: 'Μαύρο',
        microchip: 'GR000111222333444',
        description: 'Ενεργητικός, αγαπά να τρέχει.',
        traits: ['Ενεργητικός', 'Χρειάζεται χώρο'],
        age: '5',
        gender: 'male',
    },
];
